# Generated by Django 4.1.2 on 2022-12-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/%Y/%m/%d/"
            ),
        ),
    ]
