# Generated by Django 4.1.1 on 2022-10-31 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_followingrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followee",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="FollowingRelation",
        ),
    ]
