# Generated by Django 4.1.1 on 2022-10-29 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parties", "0002_party_host_alter_party_name_invitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="invitee",
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitee",
            field=models.ManyToManyField(
                related_name="invitations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
