# Generated by Django 4.1.1 on 2022-10-30 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parties", "0003_remove_invitation_invitee_invitation_invitee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"verbose_name_plural": "parties"},
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="invitee",
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
