# Generated by Django 4.1.1 on 2022-10-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0004_alter_party_options_remove_invitation_invitee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="name",
        ),
        migrations.AddField(
            model_name="invitation",
            name="acceptance",
            field=models.BooleanField(default=False),
        ),
    ]
