# Generated by Django 4.1.1 on 2022-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parties",
            "0005_remove_invitation_description_remove_invitation_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="acceptance",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
