# Generated by Django 4.1.1 on 2022-10-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0006_alter_invitation_acceptance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="acceptance",
        ),
    ]
