# Generated by Django 4.1.1 on 2022-10-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pantries", "0004_delete_statusingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pantry",
            options={},
        ),
    ]
