# Generated by Django 4.1.1 on 2022-11-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certification_recipe",
                to="recipes.recipe",
            ),
        ),
    ]
