# Generated by Django 4.1.1 on 2022-10-29 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes_user",
            field=models.ManyToManyField(
                related_name="likes_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
