# Generated by Django 4.1.1 on 2022-11-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        ("foods", "0001_initial"),
        ("ingredients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeevaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="evaluations_user",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluations_user",
                through="recipes.RecipeEvaluation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="foods.food",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.TypeIngredient",
                to="ingredients.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="likes_user",
            field=models.ManyToManyField(
                blank=True, related_name="likes_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="typeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="recipe_ingredient_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeevaluation",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="recipe_evaluation"
            ),
        ),
    ]
