# Generated by Django 4.1.1 on 2022-11-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0003_alter_recipe_evaluations_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="evaluations_user",
            field=models.ManyToManyField(
                blank=True,
                related_name="evaluations_user",
                through="recipes.RecipeEvaluation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipeevaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
