# Generated by Django 4.1.1 on 2022-10-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_category",
                    models.CharField(
                        choices=[
                            ("한식", "한식"),
                            ("양식", "양식"),
                            ("일식", "일식"),
                            ("중식", "중식"),
                            ("분식", "분식"),
                            ("베이킹", "베이킹"),
                            ("기타", "기타"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_category", models.CharField(default="", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("*", "*"),
                            ("**", "**"),
                            ("***", "***"),
                            ("****", "****"),
                            ("*****", "*****"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "cooktime_hour",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "cooktime_minute",
                    models.CharField(
                        choices=[
                            ("10", "10"),
                            ("20", "20"),
                            ("30", "30"),
                            ("40", "40"),
                            ("50", "50"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recipe",
                        to="food.food",
                    ),
                ),
                (
                    "ingredient",
                    models.ManyToManyField(
                        related_name="food_ingredient", to="ingredient.ingredient"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="food.machinecategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="food_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.foodcategory"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "comment_food",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.food",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
